server:
  port: 9010

scheduler:
  enabled: true

# -- Default spring configuration
spring:
  application:
    name: gateway
  kafka:
    bootstrap-servers: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=35S6PJG6E3XR5THT password=Qn+xRzK/S/+ThYnxC657UDGSIzFDwt/Y/N69i2CNvBUOpbV99wZwsRKytdrUJyWu;
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379